{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "esgh.serviceAccountName" . }}
  #name: platform-featureflag-esgh
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "esgh.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}