apiVersion: v1
kind: Service
metadata:
  name: {{ include "esgh.fullname" . }}-svc
  namespace: {{ .Values.app.namespace }}
  labels:
{{ include "esgh.labels" . | indent 4 }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName | default "http" }}
  selector:
    {{- toYaml .Values.service.labels | nindent 4 }}