{{- if .Values.app.certs }}
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: {{ .Values.app.akvCertSecretName }}
  namespace: istio-system
spec:
  vault:
    name: {{ .Values.app.akvVault }}
    object:
      name: {{ .Values.app.akvCertSecretName }}
      type: certificate
  output:
    secret:
      name: {{ .Values.app.akvCertSecretName }}
      type: kubernetes.io/tls
      chainOrder: ensureserverfirst
{{- end }}