{{- if .Values.app.AKVSecretsStorageAccount }}
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ .Values.app.AKVSecretsStorageAccount.AKVSecretName }}
  namespace: {{ .Values.app.namespace }}
spec:
  vault:
    name: {{ .Values.app.akvVault }} # name of  vault
    object:
      name: {{ .Values.app.AKVSecretsStorageAccount.storageAccountKey }} # name of the secret needs to be created in app namespace
      type: secret # akv object type
  output:
    secret: 
      name: {{ .Values.app.AKVSecretsStorageAccount.StorageAccountSecretNameForPod }}
      dataKey: {{ .Values.app.AKVSecretsStorageAccount.secretKeyName }}
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ .Values.app.AKVSecretsStorageAccount.AKVSecretName }}
  namespace: {{ .Values.app.namespace }}
spec:
  vault:
    name: {{ .Values.app.akvVault }} # name of  vault
    object:
      name: {{ .Values.app.AKVSecretsStorageAccount.storageAccountName }} # name of key in vault
      type: secret # akv object type
  output:
    secret: 
      name: {{ .Values.app.AKVSecretsStorageAccount.StorageAccountSecretNameForPod }}
      dataKey: {{ .Values.app.AKVSecretsStorageAccount.secretAccountName }}
{{- end}}
