name: oneclick_deploy_nonprod

on:
  workflow_dispatch:
    inputs:
      dev:
        type: boolean
        description: 'deploy dev'
        required: false
        default: 'true'
      stage:
        type: boolean
        description: 'deploy stage'
        required: false
        default: 'true'
      TAG:
        type: string
        description: 'Enter the ARC image tag to push to ACR'
        required: false
        default: ''

jobs:
  Extract_branch:
    uses: albertsons/esgh-central-workflow-gke/.github/workflows/extractbranch.yml@v3
  dev-deploy:
    needs: [Extract_branch]  
    if: success() && github.event.inputs.dev == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod.yml@v3
    with:
      ACTIONSFILE: "Actionsfile/dev"
      TAG: ${{ github.event.inputs.TAG }}
      # TAG: "${{ needs.Extract_branch.outputs.branch_name }}-${{ github.run_number }}"
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }}
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
  stage-deploy:
    needs: [Extract_branch]  
    if: success() && github.event.inputs.stage == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod.yml@v3
    with:
      ACTIONSFILE: "Actionsfile/stage"
      TAG: ${{ github.event.inputs.TAG }}
      # TAG: "${{ needs.Extract_branch.outputs.branch_name }}-${{ github.run_number }}"
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }}
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  Deploy-Status-check-dev:
    needs: [ dev-deploy ]
    if: success() && github.event.inputs.dev == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@v4
    with:
      ACTIONSFILE: "Actionsfile/dev"
    secrets:
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  Deploy-Status-check-stage:
    needs: [ stage-deploy ]
    if: success() && github.event.inputs.stage == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@v4
    with:
      ACTIONSFILE: "Actionsfile/stage"
    secrets:
      KUBECONFIG: ${{ secrets.ESCO_AKSSHARED_NONPROD_WESTUS_CLUSTER_01 }}
      PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
